on:
    push:
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml
name: CrossMgr_Build
jobs:
    buildwindows:
        name: Windows
        runs-on: windows-latest
        steps:
            - name: Setup Python environment
              uses: actions/setup-python@v1.1.1
              with:
                python-version: 3.7.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -setupenv
            - name: Build project
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -setupenv
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release.txt
                  files: release/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
