on:
    push:
        branches:
            - dev
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml

name: DevelopmentBuild
jobs:
    buildmac:
        name: MacOSX
        runs-on: macos-latest
        steps:
            - name: Show Environment
              uses: hmarr/debug-action@v1.0.0
            - name: Setup Python environment
              uses: actions/setup-python@v1.1.1
              with:
                python-version: 3.7.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -a -A
            - name: Dev Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                 repo_token: "${{ secrets.GITHUB_TOKEN }}"
                 automatic_release_tag: "latest"
                 prerelease: true
                 title: "Development Build"
                 files: release/*
