on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build CrossMgr and Tools

jobs:
  buildmac:
    name: Build MacOSX
    runs-on: macos
    steps:
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7.*
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Environment
        run: |
          cd $GITHUB_WORKSPACE
          bash compile.sh -S
      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE
          bash compile.sh -a -A
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*.dmg
          draft: true
          body_path: .github/release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  buildlinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.6.*
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Environment
        run: |
          cd $GITHUB_WORKSPACE
          bash compile.sh -S
      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE
          bash compile.sh -a -A
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*.AppImage
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
